{{- if .Values.web.hpa.enabled -}}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "web.fullname" . }}
spec:
  minReplicas: {{ .Values.web.hpa.minReplicas }}
  maxReplicas: {{ .Values.web.hpa.maxReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "web.fullname" . }}
  metrics:
    {{- toYaml .Values.web.hpa.metrics | nindent 6 }}
  behavior:
    scaleDown:
      {{- toYaml .Values.web.hpa.scaleDown | nindent 8 }}
    scaleUp:
      {{- toYaml .Values.web.hpa.scaleUp | nindent 8 }}
{{- end }}
